export function Projects() {
  return (
    <div>
      <h1 id="projects">Projects</h1>

      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
      <div>PPPPPP</div>
    </div>
  );
}
