export default function About() {
  return (
    <div>
      <h1 id="about" style={{ top: '-90px' }}>
        About
      </h1>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <h1 id="projects" style={{ top: '-90px' }}>
        About
      </h1>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
      <div>AAAAAAAAA</div>
    </div>
  );
}
